FROM openjdk:11-jre-slim

VOLUME /tmp

EXPOSE 8080

ARG JAR_FILE=target/gw-0.0.1-SNAPSHOT.jar

ADD ${JAR_FILE} gw.jar

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-Dserver.port=8080", "-jar","/gw.jar"]
